# Generated by Django 5.2.8 on 2025-11-18 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_popular', models.CharField(help_text='Nome popular da planta', max_length=200, verbose_name='Nome Popular')),
                ('nome_cientifico', models.CharField(blank=True, help_text='Nome científico da planta (opcional)', max_length=200, null=True, verbose_name='Nome Científico')),
                ('familia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Família')),
                ('dificuldade', models.CharField(choices=[('facil', 'Fácil'), ('media', 'Média'), ('dificil', 'Difícil')], default='media', max_length=10, verbose_name='Dificuldade de Cultivo')),
                ('necessidade_agua', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10, verbose_name='Necessidade de Água')),
                ('necessidade_luz', models.CharField(choices=[('sombra', 'Sombra'), ('meia_sombra', 'Meia Sombra'), ('sol_pleno', 'Sol Pleno')], default='meia_sombra', max_length=15, verbose_name='Necessidade de Luz')),
                ('temperatura_minima', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(50)], verbose_name='Temperatura Mínima (°C)')),
                ('temperatura_maxima', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(50)], verbose_name='Temperatura Máxima (°C)')),
                ('descricao', models.TextField(blank=True, help_text='Descrição geral da planta', null=True, verbose_name='Descrição')),
                ('dicas_cultivo', models.TextField(blank=True, help_text='Dicas específicas para o cultivo', null=True, verbose_name='Dicas de Cultivo')),
                ('toxica', models.BooleanField(default=False, help_text='Marque se a planta é tóxica para humanos ou animais', verbose_name='Tóxica')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
                'ordering': ['nome_popular'],
            },
        ),
    ]
