# Generated by Django 5.2.8 on 2025-12-02 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0002_comentario_delete_dicacultivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('CONTEUDO_INADIPROPRIO', 'Conteúdo impróprio'), ('INFORMACAO_FALSA', 'Informação falsa'), ('SPAM', 'Spam'), ('COPYRIGHT', 'Violação de copyright'), ('FOTO_PERFIL', 'Foto de perfil inadequada')], max_length=25)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição detalhada')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('resolvida', models.BooleanField(default=False)),
                ('comentario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plantas.comentario')),
                ('denunciador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_feitas', to=settings.AUTH_USER_MODEL)),
                ('perfil_reportado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_recebidas', to=settings.AUTH_USER_MODEL)),
                ('planta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plantas.planta')),
            ],
            options={
                'verbose_name': 'Denúncia',
                'verbose_name_plural': 'Denúncias',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Foto de Perfil')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Bio')),
                ('localizacao', models.CharField(blank=True, max_length=100, verbose_name='Cidade/Estado')),
                ('nivel_experiencia', models.CharField(choices=[('INICIANTE', '🌱 Iniciante'), ('INTERMEDIARIO', '🌿 Intermediário'), ('AVANCADO', '🌳 Avançado')], default='INICIANTE', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoritoPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritado_por', to='plantas.planta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'unique_together': {('planta', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='LikePlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='plantas.planta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
                'unique_together': {('planta', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='Seguir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguindo', to=settings.AUTH_USER_MODEL)),
                ('seguindo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguir',
                'verbose_name_plural': 'Seguidores',
                'unique_together': {('seguidor', 'seguindo')},
            },
        ),
    ]
