# Generated by Django 5.2.8 on 2025-12-02 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0004_badge_userbadge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SEGUIR', 'Novo seguidor'), ('LIKE', 'Sua planta foi curtida'), ('COMENTARIO', 'Novo comentário na sua planta'), ('BADGE', 'Você ganhou uma conquista')], max_length=20)),
                ('mensagem', models.CharField(max_length=255)),
                ('dados_json', models.JSONField(blank=True, default=dict)),
                ('lida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-lida', '-criada_em'],
            },
        ),
    ]
