# Generated by Django 5.2.8 on 2025-12-09 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0005_notificacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField()),
                ('icone', models.CharField(default='🏆', max_length=5)),
                ('tipo', models.CharField(choices=[('POSTAGENS', 'Postagens'), ('LIKES', 'Likes'), ('SEGUIDORES', 'Seguidores'), ('BADGES', 'Badges'), ('ATIVIDADE', 'Atividade'), ('ESPECIAL', 'Especial')], max_length=15)),
                ('pontos', models.IntegerField(default=10)),
                ('rara', models.CharField(choices=[('COMUM', 'Comum'), ('RARA', 'Rara'), ('EPICA', 'Épica'), ('lendaria', 'Lendária')], default='COMUM', max_length=10)),
                ('criterio', models.CharField(help_text="Ex: '5_postagens', '10_likes'", max_length=100)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conquista',
                'verbose_name_plural': 'Conquistas',
                'ordering': ['tipo', 'pontos'],
            },
        ),
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=500)),
                ('descricao', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquetes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enquete',
                'verbose_name_plural': 'Enquetes',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REGAR', 'Regar'), ('FERTILIZAR', 'Fertilizar'), ('PODAR', 'Podar'), ('REPOR_VASO', 'Repor vaso'), ('OUTRO', 'Outro')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('frequencia', models.CharField(choices=[('DIARIO', 'Diário'), ('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal'), ('ANUAL', 'Anual'), ('UNICO', 'Único')], default='UNICO', max_length=10)),
                ('proxima_data', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lembretes', to='plantas.planta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lembrete',
                'verbose_name_plural': 'Lembretes',
                'ordering': ['proxima_data'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(blank=True, max_length=200)),
                ('conteudo', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to=settings.AUTH_USER_MODEL)),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='OpcaoEnquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('ordem', models.IntegerField(default=0)),
                ('votos', models.IntegerField(default=0)),
                ('enquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='plantas.enquete')),
            ],
            options={
                'verbose_name': 'Opção de Enquete',
                'verbose_name_plural': 'Opções de Enquetes',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('publica', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('plantas', models.ManyToManyField(blank=True, related_name='colecoes', to='plantas.planta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colecoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coleção',
                'verbose_name_plural': 'Coleções',
                'unique_together': {('usuario', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='DiarioPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('titulo', models.CharField(max_length=200)),
                ('anotacao', models.TextField(blank=True)),
                ('regou', models.BooleanField(default=False)),
                ('fertilizou', models.BooleanField(default=False)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='diario/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Altura (cm)')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura (°C)')),
                ('umidade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Umidade (%)')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diario', to='plantas.planta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diário de Planta',
                'verbose_name_plural': 'Diários de Plantas',
                'ordering': ['-data'],
                'unique_together': {('planta', 'usuario', 'data')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioConquista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desbloqueada_em', models.DateTimeField(auto_now_add=True)),
                ('conquista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantas.conquista')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conquista do Usuário',
                'verbose_name_plural': 'Conquistas dos Usuários',
                'unique_together': {('usuario', 'conquista')},
            },
        ),
        migrations.CreateModel(
            name='VotoEnquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('opcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantas.opcaoenquete')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voto de Enquete',
                'verbose_name_plural': 'Votos de Enquetes',
                'unique_together': {('usuario', 'opcao')},
            },
        ),
    ]
